### ISSUE TITLE
math code:  wrong sign in \belowdisplayskip 

### ISSUE THREAD

**Issue by u-fischer** [latex3/tagging-project#11]
~~~~
\DocumentMetadata{testphase={math}}
\ExplSyntaxOn
% provide some tag internals as the math code doesn't properly guard that ...
\int_new:N\g__tag_para_end_int
\bool_new:N \l__tag_para_show_bool
\ExplSyntaxOff
\documentclass{article}

\begin{document}\showoutput
Eaque laboriosam necessitatibus itaque suscipit modi.
\[a+b=c.\]
Non reprehenderit tempora corporis perspiciatis cum quod aut.
\end{document}
~~~~

gives with the math code

![image](https://github.com/latex3/tagging-project/assets/4047173/3970cb06-b8a7-4efc-bc34-efb6cc26b8a6)

and without the math code:

![image](https://github.com/latex3/tagging-project/assets/4047173/51dd9f2b-42d7-4baa-9fb2-e1085234db69)

Looking at the output one can see that the sign of the inserted `\belowdisplayskip` is reversed:

~~~~
...\glue(\belowdisplayskip) -10.0 plus -2.0 minus -5.0
~~~~

versus

~~~~
...\glue(\belowdisplayskip) 10.0 plus 2.0 minus 5.0
~~~~

**Comment by car222222** [comment]
You say that this bug is in "the math-code from latex-lab".  If you can be a bit more precise about where to look then I can probably find it.

**Comment by car222222** [comment]
I guess you are saying that somehow `\belowdisplayskip` itself gets this "negative value".  Really strange, but easy to search for.

**Comment by car222222** [comment]
Well, I found this comment!! 

% we have to flip the sign on the skip because we flipped it on the outside

and indeed flipped it is "on the outside" -- in the everydisplay.

So it seems that anti-flipping may be needed in other places.  But currently I have no idea why it ever gets flipped :-(. I shall try to find out.

**Comment by car222222** [comment]
Noting also that there are other reasons why the current version of `latex-lab-math` is not safe to use: it is mostly OK except for a few edge cases but there are other unfixed problems, such as with the `url` package.
