### ISSUE TITLE
hang option of footmisc errors

### ISSUE THREAD

**Issue by u-fischer** [latex3/tagging-project#12]
~~~~
\DocumentMetadata{uncompress,testphase=new-OR}
\documentclass{article}
\usepackage[hang]{footmisc} 
\begin{document}
\footnote{blub} 
\end{document}
~~~~

errors with

~~~~
-> The hook 'fntext/end':
> The hook is empty.

-> The hook 'fntext/after':
> The hook is empty.
! A <box> was supposed to be here.
<to be read again> 
                   \tex_global:D 
l.142 \footnote{blub}
~~~~

**Comment by bardwnb** [comment]
footmisc also seems to give up and remove it's formatting in addition to giving the "A \<box\> was supposed to be here." error for ever footnote. In the below example, the footnote is formatted without the requested hanging indent.

```
\DocumentMetadata{testphase=phase-III}
\documentclass[a4paper]{report}


\usepackage[hang,ragged]{footmisc}
\begin{document}
Test\footnote{test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test}
\end{document}
```

**Comment by FrankMittelbach** [comment]
This is due to the fact that the tagging code uses a different implementation for footmisc, but in in case of the hang option still  (incorrectly) patches that implementation because it looks like one that "needs" patching. 

I.e., latex-lab-footmisc.ltx if loaded would need to prevent that patching from happening.

For now the workaround would be to do
```
\ExplSyntaxOn
 \cs_set_eq:NN \__fnote_patch: \prg_do_nothing:
\ExplSyntaxOff
```
when loading footmisc.

**Comment by FrankMittelbach** [comment]
Actually, that workaround does not work if the scrartcl class is used, because it prevents patching that class (but the class overwrites what footmisc does, sigh). Have now implemented the patching differently so that this is avoided.
