### ISSUE TITLE
testphase=math decreases space after math environment with blank line

### ISSUE THREAD

**Issue by mbertucci47** [latex3/tagging-project#122]
I don't know if this is a bug because I don't know which behavior is correct (or rather desired), but if the math tagging code is loaded, the amount of space after a math environment is decreased if a blank line follows the environment. You can see the difference by comment/uncommenting the "math" option in the following example.
```tex
\DocumentMetadata
  {
    lang=en-US,
    pdfversion=2.0,
    pdfstandard=ua-2,
    testphase={phase-III,
      math % comment/uncomment
      }
  }
\documentclass{article}

\begin{document}

\begin{equation}
f \to g
\end{equation}

\begin{equation}
f\to g
\end{equation}

A sentence that's long enough to get next to the math 
\end{document}
```
A few possibly unexpected things for the user happen when blank lines are removed.
- If all the blank lines are removed, the spacing is the same with or without the math tagging.
- (With or without math tagging) If the blank line between the two equations is removed, the spacing decreases.
- (With math tagging) If the blank line between the second equation and text is removed, the spacing is the same but the indent is removed.
- (Without math tagging)  If the blank line between the second equation and text is removed, the spacing decreases and the indent is removed.

It seems the behavior is the same for `\[...\]` and the amsmath environments `align`, etc.

**Comment by u-fischer** [comment]
It is the other way round: tagging without math increases the spacing with pdflatex. So

## Normal spacing without phase-III + math

![image](https://github.com/user-attachments/assets/0d23c39c-f5bc-4b07-a3ac-338537673faf)


## Wrong spacing with only phase-III

![image](https://github.com/user-attachments/assets/750ca0a5-d727-4c52-b00f-89d7df67baf5)

## Normal spacing with phase-III + math

![image](https://github.com/user-attachments/assets/7e505e08-1371-4067-a1e0-50671924855f)

With pdflatex tagging adds whatsits and they can affect spacing if in the wrong place. See also https://github.com/latex3/tagging-project/issues/10.

**Comment by FrankMittelbach** [comment]
I think we should close and in fact also close #10 because it is of no importance that phase-II without math doesn#t do the right thing if formulas are present
