### ISSUE TITLE
math code can't be used cleanly without the tagging code

### ISSUE THREAD

**Issue by u-fischer** [latex3/tagging-project#15]
~~~~
\DocumentMetadata{testphase={math}}
\documentclass{article}
\begin{document}
\[a=b\]
\end{document}
~~~~

errors with 

~~~~
! Undefined control sequence.
<argument> \g__tag_struct_tag_tl 
                                 
l.277 \[a=b\]
~~~~

This should be cleaned up, to allow better debugging.

**Comment by car222222** [comment]
More information, please!

Where does this unwanted csname come from? 
Some tracing of its origin would help a lot to fix this.

Note also that there are other outstanding questions related to "when (not) to tag math"; maybe they can all be fixed together?
