### ISSUE TITLE
math code doesn't grab \(..\)

### ISSUE THREAD

**Issue by u-fischer** [latex3/tagging-project#19]
In the following example only the first and the third math are processed, the second is ignored. Imho the setting of the boolean in `\(` is too early, as `\tex_everymath:D` is executed later.

~~~~
\DocumentMetadata{testphase={phase-III,math}}
\documentclass{article}
\begin{document}
$a=a$

\(a=b\) 

\ExplSyntaxOn\makeatletter
\cs_gset_protected:Npn \( % \)
  {
    \bool_if:NTF \l__math_collected_bool
      {
        \mode_if_math:TF
          { \@badmath }
          { $ }
      }
      {
        %\bool_set_true:N \l__math_collected_bool %looks wrong
        \__math_grab_inline:w
      }
  }
\ExplSyntaxOff
\(a=c\)
\end{document}
~~~~

from the log:

~~~~
====>first-result=macro:->a=a
====>first-tmpmathcontent=macro:->
====>formula has no subparts
====>first-result=macro:->a=c
====>first-tmpmathcontent=macro:->
====>formula has no subparts
~~~~

**Comment by car222222** [comment]
Yes, many such details have not yet been fixed.

I can try and sort it all out when I get a full spec for when collection and/or tagging should or should not happen, including edge-cases. 

Empty math is important here, especially for inline math. 

I shall also try to look for the emails between Frank and I when we last discussed this.

**Comment by car222222** [comment]
I suspect that this is not resolved in all cases.

**Comment by car222222** [comment]
The collected boolean does need to be set true, but at at a later point, just before the inline math finally gets typeset. 

Also, need to take special care in the unlikely case that the inline math is empty, in order to avoid ending up with $$, as that will start un unintended math display!

**Comment by u-fischer** [comment]
> I suspect that this is not resolved in all cases.

The issue as described in my example has been resolved. If you have some other example which fails, please open a new issue.

**Comment by car222222** [comment]
Since we do not yet have a full specification for this area, it is difficult to know whether or not something/anything "fails".

I am therefore not in any sense saying that anything will fail, just that this code still needs further changes.

These should be based on a full specification covering, for example, when the following should or should not occur: 
collection;
tagging;
typesetting (when empty).
