### ISSUE TITLE
Tables tagging

### ISSUE THREAD

**Issue by dpantele** [latex3/tagging-project#23]
It seems that tagging tables is not supported in phase-III:

```
\DocumentMetadata{testphase={phase-III,math},pdfversion=2.0,pdfstandard=A-4}

\documentclass{article}

\begin{document}
\begin{center}
\begin{tabular}{ c c c }
 cell1 & cell2 & cell3 \\ 
 cell4 & cell5 & cell6 \\  
 cell7 & cell8 & cell9    
\end{tabular}
\end{center}
\begin{table}[b]
\begin{tabular}{ c c c }
 fcell1 & fcell2 & fcell3 \\ 
 fcell4 & fcell5 & fcell6 \\  
 fcell7 & fcell8 & fcell9    
\end{tabular}
\caption{Test table}
\end{table}
\end{document}
```

produces `text` structure for both of the tables

**Comment by dpantele** [comment]
Is it the only 'standard' article environment which is not supported?

**Comment by u-fischer** [comment]
Indices are open, storing and reusing boxes, and math needs the experimental math prototype but beside this I think everything is more or less covered.

**Comment by u-fischer** [comment]
and `\marginpar` (I tend to forget that ;-)).

**Comment by FrankMittelbach** [comment]
@u-fischer I think we should really open an issue that just lists all the elements we know aren't yet done (from Lamport) in form of a table with checkmarks, so that we can simply update it whenever we have added one or the other. And if we find that we have missed one it could be added to the table.

**Comment by u-fischer** [comment]
Basic support for table tagging is now provided through the table testphase.
`testphase = {phase-III,table}`.

**Comment by u-fischer** [comment]
@dpantele better open an new issue for such questions. I can't reproduce your error, but better avoid to access the internals.  Try this instead.

~~~
\newenvironment{Tabular}[2][1]
  {\def\arraystretch{#1}\begin{tabular}{#2}}
  {\end{tabular}}
~~~

**Comment by dpantele** [comment]
Seems \begin{} and \end{} allow necessary hooks to run. Thanks!

**Comment by FrankMittelbach** [comment]
With the next version of the table tagging code it will be possible to use it also with `\tabular ... \endtabular` but for now it relies on the environment being used

**Comment by FrankMittelbach** [comment]
While the tagging code for tabulars still needs a lot more bells and whistles the basic functionality should be now available with the latest dev release.
