### ISSUE TITLE
luamplib figure tagging

### ISSUE THREAD

**Issue by mbertucci47** [latex3/tagging-project#252]
This is as much a question as an issue. The [luamplib](https://www.ctan.org/pkg/luamplib) package is listed as "compatible", however there is no provision made that `mplibcode` environments are tagged as \<Figure\>. Compare this with the `picture` environment, which has special code in latex-lab-graphic.
```tex
\DocumentMetadata
  {
    lang=en-US,
    pdfversion=2.0,
    pdfstandard=ua-2,
    testphase={phase-III,math,table,title,firstaid}
  }

\documentclass{article}
\usepackage{luamplib}

\title{luamplib tagging test}

\begin{document}

\begin{mplibcode}
beginfig(1);
draw (0,0)--(100,0)--(100,100)--(0,100)--cycle;
endfig;
\end{mplibcode}

\bigskip

\noindent
\setlength{\unitlength}{3.5cm}
\begin{picture}(1,1)
\put(0,0){\line(0,1){1}}
\put(0,1){\line(1,0){1}}
\put(1,1){\line(0,-1){1}}
\put(1,0){\line(-1,0){1}}
\end{picture}

\end{document}
```
<img width="200" alt="luamplib-struc" src="https://github.com/user-attachments/assets/355464ed-0758-48fa-b6c0-a8d221dc9ad7">

I don't know if full, useful tagging is required to be called "compatible". Should a note be added explaining the images are not tagged as Figures and the status changed to "partially-compatible"?

Furthermore, is it the responsibility of the package to provide for correct tagging here? Or is the expectation that the user will surround the environment with tagpdf declarations that correctly identify the object (artifact, figure with alt text, etc.)? This question applies to any package which produces "figures", like tikz and pstricks.

**Comment by FrankMittelbach** [comment]
You are right it should be at best partially compatible in my opinion too. the figures should tag as Figure and in addition the environmnent should support an optional argument to allow specifying alt text. Both should be mentioned in the comments
