### ISSUE TITLE
pdftitle & pdfauthor

### ISSUE THREAD

**Issue by matteofg** [latex3/tagging-project#27]
Until now I have been setting author and title metadata via `hypersetup`:
```
\DocumentMetadata{testphase=new-or-1,
  uncompress,
  lang = it-IT,
  pdfstandard = A-2a,
}

\documentclass{article}
\usepackage{hyperref}
  \hypersetup{
    pdftitle = {A Document},
    pdfauthor = {Author},
  }

\begin{document}
Hello World
\end{document}
```
I understand that with the latest tagging project updates it is possible to set author and title metadata within `DocumentMetadata`:
```
\DocumentMetadata{testphase=phase-III,
  uncompress,
  lang = it-IT,
  pdfstandard = A-2a,
  pdftitle = {A Document},
  pdfauthor = {Author},
}

\documentclass{article}
\usepackage{hyperref}

\begin{document}
Hello World
\end{document}
```
but I get the error:
```
! LaTeX Error: The key 'document/metadata/pdftitle' is unknown and is being ignored.
```
Maybe I misunderstood something...

**Comment by u-fischer** [comment]
> I understand that with the latest tagging project updates it is possible to set author and title metadata within `DocumentMetadata`

No that is a misunderstanding. The pdfmanagement code will handle the metadata and also use your values, but you still need to set them with `\hypersetup`. The general goal is to set such values in `\DocumentMetadata` (and to make them independant from hyperref), but we haven't decided yet about key names and how to organize the data.

**Comment by matteo339** [comment]
Just as I imagined. Thank you

**Comment by viktoriasee** [comment]
I think this issue can be closed. PDF ``DocumentMetadata`` and XMP Metadata are not the same. In order to create standards compatible PDFs you should use ``hyperxmp`` to handle metadata. PDF metadata is often deprecated, XMP is preferred. ``hyperxmp`` handles the exceptions.

**Comment by FrankMittelbach** [comment]
@viktoriasee what I was saying that at some point in the future we intend to make \DocumentMetadata the single go through interface to provide all the meta data for a document (which then includes also the XMP metadata)

**Comment by FrankMittelbach** [comment]
actually not saying (only indicating with "future")

**Comment by car222222** [comment]
@viktoriasee 
It may be useful also to understand that the term “metadata” is being used in several distinct ways: thus our meaning of “metadata“ here contains, additionally, other data (such as processing information) that is not normally described as  “document metadata” as it is not, in the sense of “XMPmetadata”.

**Comment by viktoriasee** [comment]
While it's clearly possible to integrate XMP metadata handling in the latex core I would just recall that metadata and accessibility is an already solved problem. The unsolved problem is tagging which to my understanding has nothing to do with metadata (at least not in the sense of ```DocumentCatalog``` or ```XMP```). 

XMP metadata is used for many things other than accessibility such as printing prepress information, engineering information, patient data, billing information and more. Many of those have national standards. I would leave this to specific packages.

**Comment by u-fischer** [comment]
@viktoriasee 

> The unsolved problem is tagging

This is not an unsolved problem. You can produce tagged PDF with LaTeX, see e.g. the documentation of tagpdf or the texlive vpat. The goal of the Tagged PDF project is not to make tagging *possible*, but to make it automatic and easy to use.
Check our [publications](https://www.latex-project.org/publications/indexbytopic/pdf/), and the LaTeX news if you want to know the current state.  

> has nothing to do with metadata

Well XMP metadata have lots of uses, but you need them also for standards like pdf/UA and so they are a part of the project.

> I would leave this to specific packages.

To late ;-).  Support for XMP metadata has been added more than a year ago to the PDF management.  Some background can be found in the tugboat article [Adding XMP metadata in LaTeX](https://www.latex-project.org/publications/2022-UFi-FMi-TUB-tb135fischer-xmp.pdf)

**Comment by viktoriasee** [comment]
> > The unsolved problem is tagging
> 
> This is not an unsolved problem.

Well… I should have clarified automated tagging. Nobody will manually tag a large document such as a PhD thesis. So from a user point of view tagging is not working yet. But I am happy you're working on it.

**Comment by FrankMittelbach** [comment]
> Well… I should have clarified automated tagging. Nobody will manually tag a large document such as a PhD thesis. So from a user point of view tagging is not working yet. But I am happy you're working on it.

@viktoriasee ... not sure you are still interested but we are now able to fully do automatic tagging if you restrict yourself to a subset of LaTeX extensions, not as large as we want it but 600+ packages and growing is not a bad start I would say and for those it is fully automatic including the math (if you use lualatex)
