### ISSUE TITLE
tagging of math in tables

### ISSUE THREAD

**Issue by u-fischer** [latex3/tagging-project#31]
Currently math formulas in tables are not handled correctly, they are either not tagged, generate warnings or even errors (display math in p-columns):

~~~~
\DocumentMetadata{testphase={phase-III,math,table}} 
\documentclass{article}
\begin{document}

\begin{tabular}[t]{l}
 $b$ \\
\end{tabular}

\begin{tabular}[t]{p{3cm}}
 \[\int=1\]  
\end{tabular}

\end{document}
~~~~

The table code can improve that by reenabling math collection at the begin of the cell:

~~~~
\DocumentMetadata{testphase={phase-III,math,table}} 
\documentclass{article}
\ExplSyntaxOn
\socket_set_plug:nnn{tagsupport/tblcell/begin}{TD}
  { \bool_set_false:N\l__math_collected_bool %added
    \tag_struct_begin:n
      {
        tag             =\l__tbl_celltag_tl,
        attribute-class =\l__tbl_cellattribute_tl
      }
    \seq_gput_right:Ne \g__tbl_struct_cur_seq { \tag_get:n {struct_num} }
    \int_step_inline:nn { \g__tbl_span_tl - 1 }
      {
        \seq_gput_right:Ne \g__tbl_struct_cur_seq { -\tag_get:n {struct_num} }
      }
    \tag_mc_begin:n{}
  }
\socket_set_plug:nnn{tagsupport/tblcell/begin}{TDpbox}
  {
    \bool_set_false:N\l__math_collected_bool %added
    \tag_struct_begin:n
      {
        tag             =\l__tbl_celltag_tl,
        attribute-class =\l__tbl_cellattribute_tl
      }
    \seq_gput_right:Ne \g__tbl_struct_cur_seq { \tag_get:n {struct_num} }
    \int_step_inline:nn { \g__tbl_span_tl - 1 }
      {
        \seq_gput_right:Ne \g__tbl_struct_cur_seq { -\tag_get:n {struct_num} }
      }
    \tagpdfparaOn
    \tl_set:Nn \l__tag_para_main_tag_tl {Div}
  }
  
\ExplSyntaxOff


\begin{document}

\begin{tabular}[t]{l}
 $b$ \\
\end{tabular}


\begin{tabular}[t]{p{3cm}}
 \[\int=1\]  
\end{tabular}

\end{document}
~~~~

This won't help if math is activated with in the tabular preamble (with `>{$}l<{$}`. And we probably need an interface command for the `\bool_set_false:N\l__math_collected_bool `.

**Comment by car222222** [comment]
I hope it is OK with everyone to comment on this one??

These ideas concerning table structures are closely related to the more general cases about which I have previously written extensively.

Currently, math collection (and probably its tagging?) nowhere distinguishes between substructures that are "true text" and 
those that are not (the "fake-text" that is often used in purely "math structures"). 

Briefly:
All (or most??) cases of "true text", such as minipages, other "text boxes", most cases of "table cells", etc., etc. are affected. 

Such substructures will need to reset all aspects of the processing of mathmode material. The last sentence, suggesting that this resetting needs a document-level version, sounds wise.  

I am not so sure that merely resetting the "collected boolean" is all that is needed to "reset all aspects . . . ", but a decision on that will have to await a full reconsideration of the relationships between the distinct aspects of this "new math processing". 

I hope this explanation is sufficiently clear.  I can elaborate if required.
