### ISSUE TITLE
\includegraphics broken with testphase=phase-III

### ISSUE THREAD

**Issue by mbertucci47** [latex3/tagging-project#32]
It seems `\includegraphics` is broken with `testphase=phase-III`. It works with `phase-II`.
```tex
\DocumentMetadata{testphase=phase-III}

\documentclass{article}

\usepackage{graphicx}

\begin{document}
\includegraphics[alt=some alt text]{example-image}
\end{document}
```
produces
```
! Undefined control sequence.
<argument> ..._graphic_int }}\__tag_prop_gput:cnx 
                                                  {g__tag_struct_\int_eval:n...
l.8 ...egraphics[alt=some alt text]{example-image}
```
The command `\__tag_prop_gput:cnx` is not defined while `\__tag_prop_gput:cne` is, I assume this is due to the recent move from "x-" to "e-type" expansion in the kernel and elsewhere.

**Comment by u-fischer** [comment]
Yes, I probably overlooked an x somewhere. Add as workaround

~~~~
\ExplSyntaxOn
\cs_generate_variant:Nn\__tag_prop_gput:Nnn{cnx}
\ExplSyntaxOff
~~~~

**Comment by kellijohnson-NOAA** [comment]
@u-fischer thank you for the quick response! I was having similar problems when using
```
testphase={phase-II,graphic}
```
Where, the error message would go away if I removed "graphic" but then I was not getting alternative text. Your suggestion worked for me🙏

**Comment by mbertucci47** [comment]
This has been fixed. Thanks
