### ISSUE TITLE
block module: item-outside-list error is not correctly setup

### ISSUE THREAD

**Issue by u-fischer** [latex3/tagging-project#35]
If one use an \item outside a list one get the error message

~~~~
! Undefined control sequence.
<argument> \__block_item_instance:n 
~~~~

If one define the command

~~~~
\DocumentMetadata{testphase={block}}
\documentclass{article}
\begin{document}

\ExplSyntaxOn
\def\__block_item_instance:n{}
\ExplSyntaxOff

\item 

\end{document}
~~~~

the message changes to

~~~~
! LaTeX Error: Unknown message 'item-in-nonlist' for module '__block'.
~~~~

**Comment by car222222** [comment]
That final message is very strangely worded!

But something like that should be the principal message.

**Comment by FrankMittelbach** [comment]
@car222222 It is not strangely worded, it is just not the message you expect seeing.  The above LaTeX error says that some L3 layer message is not found (probably misnamed), it is not saying anything about \item in the wrong place.

**Comment by car222222** [comment]
Yes, OK.  I see now why it looks strange.  Maybe it is OK for what it is.

**Comment by u-fischer** [comment]
@FrankMittelbach I would suggest to change the test and message to

~~~~
      \cs_if_free:NTF \@@_item_instance:n %%FMi?
        %{ \msg_error:nnn { @@ } { item-in-nonlist } { \item[{#1}] } }
        { 
          \@latex@error{Lonely~\string\item--perhaps~a~missing~
           list~environment}\@ehc
        }   
~~~~

This would give the  standard error:

~~~~
! LaTeX Error: Lonely \item--perhaps a missing list environment.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.181 \item x
             xx
~~~~

OK?

**Comment by car222222** [comment]
That suggested message, whilst very amusing, is somewhat too vague . . . or not?

**Comment by u-fischer** [comment]
That is the standard message you get since 30 years or so. I simply copied it from latex.ltx.

**Comment by car222222** [comment]
OK with me!

**Comment by FrankMittelbach** [comment]
> That suggested message, whilst very amusing, is somewhat too vague . . . or not?

actually you might be the one who invented it :-) or I or David at the time matching `perhaps a missing \item` with a smile

**Comment by davidcarlisle** [comment]
> > That suggested message, whilst very amusing, is somewhat too vague . . . or not?
> 
> actually you might be the one who invented it :-) or I or David at the time matching `perhaps a missing \item` with a smile

or Rainer:-)

```
% \changes{LaTeX2.09}{1991/11/04}
%         {(RmS) added default definition for \cs{makelabel},
%               to produce an error message.}
```

**Comment by FrankMittelbach** [comment]
or Rainer ... but we have all been guilty of agreeing to this message (and I still think it is a nice and matching one).

**Comment by car222222** [comment]
No guilt needed!
