### ISSUE TITLE
babel/french with hyperref causes hooks error 

### ISSUE THREAD

**Issue by John02139** [latex3/tagging-project#414]
```
\DocumentMetadata{%
	pdfstandard=a-4f,
	pdfversion=2.0,
	lang=en-US,
	testphase={phase-III},
}
\documentclass{article}
\usepackage[T1]{fontenc}

\usepackage[french,main=english]{babel} 
%\usepackage[spanish,german,polish,japanese,main=english]{babel} 

% french  triggers ! LaTeX hooks Error: Generic hooks cannot be added to '\refstepcounter', if hyperref is loaded
% spanish, german, and various other languages do not trigger this error

\usepackage{hyperref} 

\begin{document}
\section{Introduction}
    Some text.
\end{document}
```

**Comment by u-fischer** [comment]
The generic command hooks fails as the code contains a ! and french makes that active. One can avoid the error by disabling the shorthand, e.g. with `\usepackage[french,main=english,shorthands=off]{babel}`. With lualatex this is ok,  but with pdflatex it disables the spaces before the ! etc. 

A better solution is to add a proper hook to the kernel refstepcounter so that the tagging code can avoid to use a generic hook.

**Comment by John02139** [comment]
Many other babel languages make some characters active.  Among ~25 that I have tried, in various scripts, only these two (french and spanish) resulted in problems with the packages that I use.

**Comment by domix75** [comment]
Hello
I have another issue with the French babel: itemize raises an error 
here is the source
```
\DocumentMetadata{
 pdfversion=2.0,
 pdfstandard=ua-2,
 %lang=fr-FR,
 testphase=
   {
    phase-III, %lists,footnotes,sectioning,
               %toc,marginpar,bibliography,floats,
               %graphics ...
    math,
    table, %tabular, tabularx, longtable
    title  %maketitle
   }
 }

% Preamble
\documentclass[12pt, a4paper, twoside]{report}
\usepackage[french]{babel}
\usepackage[T1]{fontenc}

\renewcommand{\familydefault}{\sfdefault} %% Font sans serif par défaut (plus lisible)

\begin{document}

    Une salade de fruits:

\begin{itemize}
    \item Pomme
    \item Kiwi
    \item Fraise
    \item Ananas
\end{itemize}

\end{document}
```

compiling with lualatex-dev, texlive (just updated)
```
! LaTeX Error: Lonely \item--perhaps a missing list environment.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.29     \item P
              omme
? 
```
(and the same for the 3 other \item)

is there something I do wrong ?
cheers
d

**Comment by u-fischer** [comment]
@domix75 I moved your comment into a new issue as it is a different issue 
https://github.com/latex3/tagging-project/issues/694

**Comment by John02139** [comment]
Confirming that both issues are fixed in 2024-11-01 release, and closing.
