### ISSUE TITLE
showhyphenation package incompatible

### ISSUE THREAD

**Issue by mbertucci47** [latex3/tagging-project#435]
The [showhyphenation](https://ctan.org/pkg/showhyphenation) package breaks up the tags in a way that surely can't be good for reading aloud.
```tex
\DocumentMetadata
  {
    lang=en-US,
    pdfversion=2.0,
    pdfstandard=ua-2,
    testphase={phase-III,math,title,table,firstaid},
  }
\documentclass{article}
\usepackage{showhyphenation}
\usepackage{kantlipsum}

\begin{document}

\kant[1-5]

\end{document}
```
Not that an intentionally accessible document would be using this package...

**Comment by u-fischer** [comment]
It looks wild in acrobat, but the tagging is actually ok. There are simply lots of container for text interupted by artifacts from the red markers. 
So the uncompressed pdf looks like this 

~~~~
/Artifact BMC
1 0 0 1 207.576 633.325 cm
q 4.423 0 m 6.415 -2.988 l 2.431 -2.988 l 1 .25 .45 rg f Q
EMC
/text<</MCID 12>> BDC
1 0 0 1 -207.576 -633.325 cm
BT
/F15 9.96264 Tf
1 0 0 1 207.576 633.325 Tm [<0032004D0051>]TJ
ET
EMC
~~~~ 

A conforming processor should be able to handle that. If you e.g. upload the file to https://ngpdf.com/loadFile you can see that the text comes out quite nicely.

**Comment by mbertucci47** [comment]
Ah good to know that empty containers don't produce "spaces"
