### ISSUE TITLE
Missing % in \@starttoc

### ISSUE THREAD

**Issue by jfbu** [latex3/tagging-project#50]
Not sure if this is correct repository for this issue.

https://github.com/latex3/latex2e/blob/cc704066a05e5fb1563786558db0cd5f3e91e0ec/required/latex-lab/latex-lab-toc-kernel-changes.dtx#L233-L244

is lacking a `%` after `\@starttoc@cfgpoint@after{#1}`

```latex
\def\@starttoc#1{%
  \begingroup
    \makeatletter
    \@starttoc@cfgpoint@before{#1}%
    \@input{\jobname.#1}%
    \@starttoc@cfgpoint@after{#1} HERE
    \if@filesw
      \expandafter\newwrite\csname tf@#1\endcsname
      \immediate\openout \csname tf@#1\endcsname \jobname.#1\relax
    \fi
    \@nobreakfalse
  \endgroup}
```

**Comment by FrankMittelbach** [comment]
> Not sure if this is correct repository for this issue.

yes that one is the best repo for it (and we can reassign easily if we think not)
