### ISSUE TITLE
hypdestopt package incompatible

### ISSUE THREAD

**Issue by mbertucci47** [latex3/tagging-project#525]
The [hypdestopt](https://ctan.org/pkg/hypdestopt) package errors with `\DocumentMetadata{}` because it expects commands like `\Hy@DestName` to be defined, which I guess are not in the new generic hyperref.
```tex
\DocumentMetadata{}
\documentclass{article}
\usepackage{hyperref}
\usepackage{hypdestopt}
\begin{document}
test
\end{document}
```

**Comment by u-fischer** [comment]
Fix uploaded to ctan, hypdestopt will be ignored if \DocumentMetadata is detected, see https://github.com/ho-tex/hypdestopt/issues/2

**Comment by FrankMittelbach** [comment]
means it should be marked compatible in the table (if it is in there) - can't check now
