### ISSUE TITLE
explicitly loading array breaks `\cline`

### ISSUE THREAD

**Issue by mbertucci47** [latex3/tagging-project#605]
Explicitly loading array causes `\cline` to error with the current dev formats.
```tex
\documentclass{article}
\usepackage{array}
\begin{document}
\begin{tabular}{ccc}
A & B & C\\ \cline{1-2}
D & E & F
\end{tabular}
\end{document}
```
errors with
```
! You can't use `\relax' after \the.
<recently read> ...ort/tbl/leaders/begin_args_int 
```
If the tagging code is loaded there is no error.

Not sure if this belongs in this repo but I posted here since it's tagging-related. Please feel free to move.

**Comment by davidcarlisle** [comment]
oops thanks for that. I guess we should move this to the main latex repo (@FrankMittelbach  ?)

**Comment by davidcarlisle** [comment]
@mbertucci47  can you show your log? Initially I reproduced that error locally but I had a mix of a locally installed dev array.sty and the new updated texlive dev and were out of sync. I can't reproduce with a cleaned up input tree.

**Comment by davidcarlisle** [comment]
@mbertucci47  I could reproduce the error locally when you reported it but I was using an inconsistent input tree, with a fully up to date texlive using `LaTeX2e <2024-11-01> pre-release-2 (develop 2024-8-16 branch)` I get no error.

**Comment by mbertucci47** [comment]
You're right. When I updated texlive I had a latex-lab pdf open which caused the latex-lab-dev update to fail, and when it was reinstalled it didn't automatically regenerate formats like it usually does. Sorry for the noise
