### ISSUE TITLE
pbox package incompatible

### ISSUE THREAD

**Issue by mbertucci47** [latex3/tagging-project#628]
The `\pbox` command of [pbox](https://ctan.org/pkg/pbox) produces parent-child warnings.
```tex
\DocumentMetadata
  {
    lang=en-US,
    pdfversion=2.0,
    pdfstandard=ua-2,
    testphase={phase-III,title,math,table,firstaid}
  }
\documentclass{article}
\usepackage{pbox}

\title{pbox tagging test}

\begin{document}
\pbox[b]{0.5\textwidth}{Hello\\World!}%
\pbox[t]{0.5\textwidth}{Bonjour\\monde!}

% compare with
\parbox[b]{1.5cm}{Hello\\World!}%
\parbox[t]{1.5cm}{Bonjour\\monde!}
\end{document}
```
It is also implemented as a tabular so the tagging is unclear.

**Comment by u-fischer** [comment]
The problem is the `\settowidth` command. Imho it would make sense to generally suspend tagging there. This here looks fine:

~~~~
\DocumentMetadata
  {
    lang=en-US,
    pdfversion=2.0,
    pdfstandard=ua-2,
    testphase={phase-III,title,math,table,firstaid}
  }
\documentclass{article}
\usepackage{pbox}

\title{pbox tagging test}
\makeatletter
\def\@settodim#1#2#3{\setbox\@tempboxa\hbox{{\SuspendTagging{settodim}#3}}#2#1\@tempboxa
       \setbox\@tempboxa\box\voidb@x}
\makeatother
\begin{document}

\pbox[b]{0.5\textwidth}{Hello\\World!}%
\pbox[t]{0.5\textwidth}{Bonjour\\monde!}

% compare with
\parbox[b]{1.5cm}{Hello\\World!}%
\parbox[t]{1.5cm}{Bonjour\\monde!}
\end{document}
~~~~

@FrankMittelbach what do you think?

**Comment by FrankMittelbach** [comment]
Absolutely, it is temporary data thrown away afterwards so nothing should be tagged inside.

**Comment by u-fischer** [comment]
ok, I will add it. It is not necessary as there is a group, but do we need a \ResumeTagging anyway for debugging messages?

**Comment by FrankMittelbach** [comment]
It is a bit of unnecessary overhead, but probably better that way at least for now. Does that mean the package becomes compatible once this is added?

**Comment by u-fischer** [comment]
Yes I think it is then compatible as it then uses the parbox code (but I didn't test really carefully).

**Comment by FrankMittelbach** [comment]
Well, if it is using tabular internally, then I think it should be at best partially-compatible once that bug is fixed, because that would be a presentation-table that should not be tagged as a table I would say.

**Comment by mbertucci47** [comment]
With @u-fischer's fix for `\@settodim` the tagging looks identical for `\parbox` and `\pbox`. I think it only uses `tabular` for measuring the width, not for typesetting, so my initial comment about tabular was misleading

**Comment by FrankMittelbach** [comment]
> With @u-fischer's fix for `\@settodim` the tagging looks identical for `\parbox` and `\pbox`. I think it only uses `tabular` for measuring the width, not for typesetting, so my initial comment about tabular was misleading

that sounds a bit odd, but who knows :-) if they are coming out identical, I think we can call it compatible.

**Comment by mbertucci47** [comment]
Sounds good. I'll just note https://github.com/latex3/latex2e/pull/1457 hasn't been merged yet

**Comment by FrankMittelbach** [comment]
yes, it had to wait for an update in tagpdf ... which I think is about to be distributed. So I was a litte premature in changing the label here :-) but we should be there in a few days.

**Comment by FrankMittelbach** [comment]
Ah I see, the package uses tabular to measure the width of text that contains `\\`. Interesting idea.

**Comment by mbertucci47** [comment]
I think this is still not fixed. My initial example produces a bunch of parent-child warnings with the newest release

**Comment by FrankMittelbach** [comment]
Thanks for setting us straight @mbertucci47, so back to the drawing board

**Comment by u-fischer** [comment]
@FrankMittelbach  grumpf. We have the right `\@settodim` in the kernel but calc.sty overwrites it ... . We must suspend tagging there too.

**Comment by FrankMittelbach** [comment]
:-) yes that is something we should have remembered. But at least it is a simple fix then.
