### ISSUE TITLE
math content in `picture` environment is lost

### ISSUE THREAD

**Issue by mbertucci47** [latex3/tagging-project#661]
With math tagging loaded, any math content in a `picture` environment is lost.
```tex
\DocumentMetadata
  {
    lang=en-US,
    pdfversion=2.0,
    pdfstandard=ua-2,
    testphase={phase-III,title,math,table,firstaid}
  }
\documentclass{article}
\begin{document}
\begin{picture}[alt=a test picture](5,5)
text$x$
\end{picture}
\end{document}
```
I first noticed this in the feynmf/feynmp example in #659.

**Comment by davidcarlisle** [comment]
The input should probably be `\put(0,0){text$x$}` (although the math still vanishes) text at the top level in a picture mode doesn't generate an error for historical reasons, but doesn't really do anything sensible)

**Comment by mbertucci47** [comment]
@davidcarlisle You're right, I was just trying to make the example as minimal as possible

**Comment by josephwright** [comment]
Ah, tagging is not active inside pictures: likely one for @u-fischer

**Comment by josephwright** [comment]
```latex
~....\tag_socket_use:nn #1#2->\bool_if:NT \l__tag_active_socket_bool {\UseSocke
t {tagsupport/#1}{#2}}
#1<-math/inline/formula/begin
#2<-x

~.....\bool_if:NT #1->\if_bool:N #1\__prg_T_true:w \fi: \use_none:n 
#1<-\l__tag_active_socket_bool 
{\ifodd: (level 1) entered on line 11}
{false}
{\fi: \ifodd (level 1) entered on line 11}

~......\use_none:n #1->
#1<-\UseSocket {tagsupport/math/inline/formula/begin}{x}
{math shift character $}
```

**Comment by josephwright** [comment]
I guess we need to reset tagging status at the start of any boxes in picture mode.

**Comment by u-fischer** [comment]
it is not only picture mode. Math disappears always if tagging is suspended:

~~~~
\DocumentMetadata
  {
    lang=en-US,
    pdfversion=2.0,
    pdfstandard=ua-2,
    testphase={phase-III,title,math,table,firstaid},
    uncompress
  }
\documentclass{article}
\begin{document}

xxx \SuspendTagging{test} $a=b$ \ResumeTagging{test} aaaa

\end{document}
~~~~

![image](https://github.com/user-attachments/assets/a8af2a09-b9c6-4beb-bce5-a3c880b12f56)

**Comment by davidcarlisle** [comment]
@josephwright 
> I guess we need to reset tagging status at the start of any boxes in picture mode.

That's not clear: the outer picture env has `[alt=a test picture]` so I thought from a tagging perspective it ends there and is just a black box after that with the alt text filling in.

Don't we need to revert the math grabbing to normal  if  tagging is suspended?

**Comment by u-fischer** [comment]
@josephwright  but before I work on it I have to listen to an interesting talk

**Comment by car222222** [comment]
Are there not some larger questions here?

Concerning the tagging of the content of diagrams (as opposed to "pictures" in the non-technical sense: e.g. photos or paintings);
Because such diagrams typically consist of many structural components, including for example:
 "text" of various types;
very specific, often named, substructures (that are part of the semantics of the diagram); 
Noting that the semantic relationships between these substructures are distinct from, and more important than, any visual relationships.

At some stage, these will be coded by largely semantic markup (plus possibly some essential visual/layout hints).
