### ISSUE TITLE
`\printacronyms` errors with block environment

### ISSUE THREAD

**Issue by mbertucci47** [latex3/tagging-project#698]
If a document contains a block environment like `quote` or `equation`, and `\printacronyms` of the [acro](https://www.ctan.org/pkg/acro) package is preceded by a blank line, then you get a "number of begin and end" error. The error only seems to appear with the default `template=description`.
```tex
\DocumentMetadata
  {
    lang=en-US,
    pdfversion=2.0,
    pdfstandard=ua-2,
    testphase={phase-III,math,table,title,firstaid}
  }
\documentclass{article}
\usepackage{acro}
\DeclareAcronym{cd}{
  short = CD ,
  long = compact disc
  }
\begin{document}

\begin{quote} % or equation, etc.
Some text
\end{quote}
\ac{cd} % removing the next blank line makes the error disappear

\printacronyms
%\printacronyms[template=tabular] % this is fine

\end{document}
```
There's no problem without the tagging code.

**Comment by u-fischer** [comment]
Compiles fine for me with -dev (and also with the new tagging31-XXX  branch). So I think we can call that fixed-in-release.

**Comment by mbertucci47** [comment]
Ah sorry. I still need to get in the habit of using -dev
