### ISSUE TITLE
DocEng '24 paper on tagging publications list, tagged

### ISSUE THREAD

**Issue by nxg** [latex3/tagging-project#716]
(Part (a) of this is sufficiently obvious that I imagine it's on someone's mental issue list anyway).

It would be useful (a) if the DocEng 2024 update paper (Mittelbach et al, 'Automatically producing accessible and reusable PDFs with LATEX', <https://doi.org/10.1145/3685650.3685670>) were included in the [project publications list](https://www.latex-project.org/publications/indexbytopic/pdf/), _and_ (b) if this page noted that (presumably) the papers in this list were tagged using the new support.

A link to the paper appeared on an accessible-maths list I read, and prompted some [useful discussion](https://www.jiscmail.ac.uk/cgi-bin/wa-jisc.exe?A1=ind2409&L=ACCESSIBLE-MATHS). But one of the list participants did the obvious and sensible thing and checked to see what tagging was present in the paper, and how it read in an assistive-technologies reader.  There's none, of course because (I'm guessing) the PDF was produced using a publisher workflow which (of course) doesn't include the new support; the commenter drew some negative inferences from that.  Though I doubt much can be done about the proceedings version, it would be a good look if there were a canonical alternative version of the paper, here, which was an advert for itself  [insert some remark about dogfood here...].

I presume it's on someone's to-do list to add the paper here, so this issue is just to log the obvious suggestion that this should be an author-prepared preprint produced with tagging, rather than the proceedings version; and that this list somehow notes that these papers have that tagging, encouraging potential readers to confirm that the PDFs illustrate the support they're describing.  I suppose it would be useful to additionally indicate which version/phase of the system they're using, to avoid confusion when later phases become available.

**Comment by nxg** [comment]
Thanks for this, Ulrike: I've passed on a pointer to your comments in the list thread.

**Comment by FrankMittelbach** [comment]
> A link to the paper appeared on an accessible-maths list I read, and prompted some [useful discussion](https://www.jiscmail.ac.uk/cgi-bin/wa-jisc.exe?A1=ind2409&L=ACCESSIBLE-MATHS).

Hi Norman, is there a simple way to join that list discussion for any of us? (I have somewhat limited internet connections right now and it is difficult to research that for me).

**Comment by car222222** [comment]
I looked at this possibility, but gave up! 
So I too hope that there is an "easy way" to access elements in this truly vast collection of lists!

**Comment by nxg** [comment]
On the list archive page, I'm seeing a ‘subscribe or unsubscribe’ link in the top left, which seems to link to a subscription page, when I try it.  If you're seeing something different, something might be amiss – perhaps we should resolve that offline.

**Comment by FrankMittelbach** [comment]
A PDF/UA-2 compatible version of the paper is now on the LaTeX project site at:

https://www.latex-project.org/publications/indexbytopic/pdf/
