### ISSUE TITLE
Redefinition of \@makechapterhead Ignored When Chapter Title Contains ] in testphase={phase-III}

### ISSUE THREAD

**Issue by DavidEGx** [latex3/tagging-project#725]
When using `\DocumentMetadata{testphase={phase-III}}`, redefining `\@makechapterhead` to suppress chapter headings works as expected unless the chapter title includes a closing square bracket ].
In such cases, the redefinition is ignored, and the chapter heading appears in the output PDF.

**Example**:
```latex
\DocumentMetadata{
  lang        = en,
  pdfversion  = 2.0,
  pdfstandard = ua-2,
  testphase   = {phase-III}
}

\documentclass{report}
\usepackage{hyperref}
\makeatletter

\def\@makechapterhead#1{%
{}}

\begin{document}
\chapter{ Chapter ] }

Stuff
\end{document}
```

**Steps to Reproduce**:

1. Compile the above example with LaTeX using the latest packages.
2. Observe that the chapter heading "Chapter ]" appears in the PDF output, despite the redefinition of \@makechapterhead.

**Expected Behavior**:

The redefinition of \@makechapterhead should suppress the chapter heading, regardless of the content of the chapter title, including special characters like ].

**Notes**:
- The issue does not occur when testphase={phase-III} is omitted.
- The issue does not occur if the chapter title does not contain the ] character.

**Comment by u-fischer** [comment]
actually `\chapter{ Chapter ] }` breaks even without your redefinition as there is a brace pair missing in the code. Until this is corrected hide the bracket in  braces: `\chapter{ Chapter {]} }`

But beside this, what structure do you want to get from your redefinition? Currently your code creates a Sect structure with a chapter structure element without content as child.

~~~~
![image](https://github.com/user-attachments/assets/add2613e-5cea-431b-8d1c-de6455ec58f2)

**Comment by DavidEGx** [comment]
Not really trying to achieve anything in particular.
Just inherit some insane latex code and asked to make it accessible (😱).

I've noticed a visual difference in the generated PDFs with and without `testphase` and worked out that minimal example.

I guess you are saying it doesn't make sense to redefine the chapter that way because it will generate a pointless tag. Hence the pdf won't be really accessible 😔.
