### ISSUE TITLE
amsthm firstaid style issues

### ISSUE THREAD

**Issue by mbertucci47** [latex3/tagging-project#733]
The amsthm firstaid seems to work well. I tested the amsthm file thmtest.tex and found only two issues. It seems the "space above" and "space below" parameters of `\newtheoremstyle` are not respected at all. Also, if a custom head spec is given in `\newtheoremstyle`, then the head punctuation is ignored and parent-child warnings are produced. Here's an example.
```tex
\DocumentMetadata
  {
    lang=en-US,
    pdfversion=2.0,
    pdfstandard=ua-2,
    testphase={phase-III,math,table,title,firstaid}
  }
\documentclass{article}
\usepackage{amsthm}

\newtheoremstyle{citing}% name
  {20pt}%      Space above, empty = `usual value'
  {3pt}%      Space below
  {\itshape}% Body font
  {}%         Indent amount (empty = no indent, \parindent = para indent)
  {\bfseries}% Thm head font
  {.}%        Punctuation after thm head
  {.5em}%     Space after thm head: " " = normal interword space;
        %       \newline = linebreak
  {\thmnumber{#2 }\thmname{#1}\thmnote{: #3}}% Thm head spec

\theoremstyle{citing}
\newtheorem{theorem}{Theorem}

\begin{document}

\begin{theorem}
text
\end{theorem}
text
\begin{theorem}[some note]
text
\end{theorem}

\end{document}
```
As you can see, the `20pt` space above is ignored, and there is no period after the theorem head.

**Comment by mbertucci47** [comment]
I think the space parameters are ignored because they are used to set `\@topsep` and `\@topsepadd` which the firstaid code doesn't use because the theorem is no longer implemented as a trivlist (please correct me if I'm wrong).

**Comment by FrankMittelbach** [comment]
that sounds like a very likely cause (not being able to look right now)

**Comment by mbertucci47** [comment]
And I think the head punctuation is ignored because `\the\thm@headpunct` was moved into `\thmhead@plain` but is not accounted for with other `\thmhead`s.

**Comment by u-fischer** [comment]
@FrankMittelbach  handling the topspace is rather easy, I simply need to pass the value to the instance call. But I'm not sure what to do about the space below. `end-skip` seems to do nothing:

~~~~
\DocumentMetadata
  {
    lang=en-US,
    pdfversion=2.0,
    pdfstandard=ua-2,
    testphase={phase-III,math,table,title,firstaid}
  }
\documentclass{article}
\begin{document}
xxxxx
\begin{enumerate}[end-skip=50pt]
\item blub
\end{enumerate}
xxxxx

\end{document}
~~~~

**Comment by mbertucci47** [comment]
The firstaid code defines `\thmname` etc. to tag their contents but does not wrap it in a `Caption` struct if `\thmhead` is not `\thmhead@plain`, since `\tag_struct_begin:n{tag=Caption}` is set in `\thmhead@plain` but not otherwise.

**Comment by mbertucci47** [comment]
So that chunk of code could instead be
```tex
    \def\@begintheorem##1##2[##3]{%
      \UseInstance{blockenv}{theorem}{}
      \tagpdfparaOff
      \mode_leave_vertical:
      \MakeLinkTarget{\l__block_thm_current_counter_tl}
      \group_begin:
      \normalfont
      \the\thm@headfont \thm@indent
        \@ifempty{##1}
         {\let\thmname\@gobble}
         {\def\thmname####1{\tag_mc_begin:n {}####1\tag_mc_end:}}%
        \@ifempty{##2}
         {\let\thmnumber\@gobble}
         {\def\thmnumber####1
           {\tag_struct_begin:n{tag=Lbl}\tag_mc_begin:n {}
             ####1
            \tag_mc_end:\tag_struct_end:}}%
        \@ifempty{##3}
         {\let\thmnote\@gobble}
         {\def\thmnote####1{\tag_mc_begin:n{}####1\tag_mc_end:}}%
        \tag_struct_begin:n{tag=Caption}%
        \thm@swap\swappedhead\thmhead{##1}{##2}{##3}%
        \tag_struct_end:%
        \thmheadnl % possibly a newline.
        \hskip\thm@headsep
      \group_end:
       \tagpdfparaOn
       \UseTaggingSocket{para/begin}  %
      \ignorespaces}
    \def\thmhead@plain##1##2##3{%
      \thmname{##1}
      \thmnumber{
        \@ifnotempty{##1}{~}\@upn{##2}
       }%
      \thmnote{\pdffakespace\space{\the\thm@notefont(##3)}}
      %moved for easier tagging
      \tag_mc_begin:n{}\the\thm@headpunct\tag_mc_end:
      }
    \let\thmhead\thmhead@plain
    \def\swappedhead##1##2##3{%
      \thmnumber{##2}
      \thmname{\@ifnotempty{##2}{\nobreakspace}##1}
      \thmnote{\pdffakespace\space{\the\thm@notefont(##3)}}
      \tag_mc_begin:n{}\the\thm@headpunct\tag_mc_end:
     }
```
where `\tag_struct_begin:n{tag=Caption}` and `\tag_struct_end:` are moved inside `\@begintheorem`, out of `\thmhead@plain` and `\swappedhead`.

**Comment by wystanical** [comment]
The accepted answer to [this tex.stackexchange question](https://tex.stackexchange.com/questions/726024/is-there-a-theorem-package-that-works-with-tagpdf) show successful compilation of TeX code using amsthm. On the other hand the tagging it produces breaks a rule that Acrobat Pro complains about; "Lbl and LBody must be children of LI".

I absolutely don't know enough to decide how serious this issue is, but I thought I should report it.

**Comment by u-fischer** [comment]
@wystanical  the document is PDF 2.0 and the use of Lbl is correct,  verapdf for example would not complain. But it is naturally a bit of a problem that Acrobat can't handle pdf 2.0 properly. In the case of section numbers we actually removed the use of Lbl just to avoid the warnings from Acrobat and perhaps we will have to do this here too if Acrobat doesn't improve its PDF 2.0 handling.

**Comment by FrankMittelbach** [comment]
Another way to say this is that you should report to Adobe that their software gets fixed and understands the PDF2.0 standard (which isn't that young). But even there (in PDF1.7) it is not correct that Lbl is only allowed in lists -- it is the primary use case, yes, but the standard gives other examples of Lbl, e.g. as part of notes or TOC or bib entries, so the statement "Lbl and LBody must be children of LI" is simply not correct.
