### ISSUE TITLE
starred `\newtheorem` produces warnings with hyperref

### ISSUE THREAD

**Issue by mbertucci47** [latex3/tagging-project#736]
If hyperref is loaded, the starred `\newtheorem` produces a warning
```
Package hyperref Warning: Counter '' or the representation '\theH`
(hyperref)                don't exist. No target created.
```
Here's an example.
```tex
\DocumentMetadata
  {
    lang=en-US,
    pdfversion=2.0,
    pdfstandard=ua-2,
    testphase={phase-III,math,table,title,firstaid}
  }
\documentclass{article}
\usepackage{amsthm}
\usepackage{hyperref}

\newtheorem*{theorem}{Theorem}

\begin{document}

\begin{theorem}
text
\end{theorem}

\end{document}
```
This happens because the redefined `\@begintheorem` unconditionally calls `\MakeLinkTarget{\l__block_thm_current_counter_tl}`. With an unnumbered theorem `\l__block_thm_current_counter_tl` is empty. I guess changing this line to `\tl_if_empty:nF{##2}{\MakeLinkTarget{\l__block_thm_current_counter_tl}}` is enough.

**Comment by u-fischer** [comment]
good catch and good timing ;-) I just adjusted the firstaid anyway.
