### ISSUE TITLE
! Package tagpdf Error: there is no open structure on the stack

### ISSUE THREAD

**Issue by baskar-67** [latex3/tagging-project#743]
How can I resolve the following error when using the amsthm package?
! Package tagpdf Error: there is no open structure on the stack

Type <return> to continue.
 ...

l.199 \end{lemma}

Thanks and regards
Baskaran NK

**Comment by u-fischer** [comment]
> How can I resolve the following error when using the amsthm package?

The first step is to show a small, complete example that demonstrates what you are actually doing and to show also the complete log-file so that we can see which versions you use.

Beside this you can try to add  `testphase=firstaid` to the `\DocumentMetadata` command and to compile with the newest lualatex-dev, it contains some support for amsthm.

**Comment by u-fischer** [comment]
You should update your tex system. You are using `LaTeX2e <2024-11-01> pre-release-3 (develop 2024-10-8 branch)`, but for amsthm support you need `LaTeX2e <2024-11-01> pre-release-4 (develop 2024-10-21 branch)`.

**Comment by baskar-67** [comment]
I have installed pre-release-4. Only one the below error shows:

! LaTeX Error: Mismatched LaTeX support files detected.
(LaTeX)        Loading 'expl3.sty' aborted!
(LaTeX)        
(LaTeX)        The L3 programming layer in the LaTeX format
(LaTeX)        is dated 2024-09-10, but in your TeX tree the files require
(LaTeX)        at least 2024-10-09.

If I update the expl3.sty file date in my current folder, it works fine. However, I need the date to be 2024-10-09, but the version available on CTAN is dated 2024-09-10.
Thanks and regards
Baskaran NK

**Comment by josephwright** [comment]
@baskar-67  The CTAN `l3kernel` is as you say 2024-09-10, but the dev release is 20204-10-09 - it looks to me as though you've mixed files from the two up. Can you show your `.log`?

**Comment by baskar-67** [comment]
I have attached sample.log 
[sample.log](https://github.com/user-attachments/files/17473017/sample.log)

Thanks and regards
Baskaran NK

**Comment by josephwright** [comment]
@baskar-67 You need to rebuild your `dev` formats

**Comment by baskar-67** [comment]
Hi Sir,
After rebuilding the format file, everything is now working fine. Initially, running fmtutil-sys --all resulted in a ‘Scripts not found’ error. I then ran tlmgr install texlive-scripts and subsequently ran fmtutil-sys --all again, which successfully rebuilt all format files.
Thanks and regards
Baskaran NK
