### ISSUE TITLE
Validation by Verapdf and Arlington fail, but for different reasons (V/a-4: equation and A: includegraphics)

### ISSUE THREAD

**Issue by John02139** [latex3/tagging-project#744]
I realize the PDF/2.0 validators are a work in progress, but I thought it might be helpful to mention some inconsistencies.

- Arlington flunks \includegraphics (both a-4 and ua-2 levels)
- VeraPdf flunks a simple equation at a-4 level but passes it at ua-2 level

By commenting out different parts of the example below, one or the other validator can be made to pass.

```
%% Tested with Arlington 1.27.96 and https://demo.verapdf.org/ (1.26.1)

\DocumentMetadata 
{
	testphase={phase-III,math,table,title,firstaid},
	pdfstandard = a-4,%ua-2,
	pdfversion  = 2.0,
	lang	    = en-US,
}

\documentclass[11pt]{article}
\usepackage{graphicx}

\begin{document}
\title{A Title}
\maketitle

Some main text.

%% equation passes arlington and verapdf/ua-2 but fails verapdf/a-4 
\begin{equation} 
F = ma
\end{equation}

%%% includegraphics passes verapdf but fails arlington
\begin{figure}[h]
% sample image is from mwe package, but is in the tex tree w/o loading that package
\centering\includegraphics[width=7cm,alt={Example image}]{example-image-b} 
\caption{Figure caption text}
\end{figure}

\end{document}  
```
A report from verapdf is:

<img width="1132" alt="Screenshot 2024-10-21 at 12 52 56 PM" src="https://github.com/user-attachments/assets/93d1d5a4-13f9-4073-8337-e7e058689517">

A report from Arlington is:

<img width="888" alt="Screenshot 2024-10-21 at 1 11 08 PM" src="https://github.com/user-attachments/assets/96081d1c-7fff-402a-b738-1c8d642c4a1e">

**Comment by u-fischer** [comment]
As mentioned in the l3pdfmeta documentation (that is the module that setups standards) the key declares a standard but can't neither enforce all the requirements nor check if all are followed. In this case you are inputting a pdf which is not standard compliant and so validation fails. (But I will check the middle failure to ensure that this is not an engine problem).

**Comment by John02139** [comment]
Thanks, Ulrike.  I will be interested in your analysis of the VP/a-4 issue.

**Comment by u-fischer** [comment]
the math leads to validation errors as it embeds associated files (mathml and texsource). In this case you need the `a-4f` standard.

**Comment by John02139** [comment]
Ahh, of course!  Sorry for this oversight.
