### ISSUE TITLE
abstract box placed near root tag instead of after \date

### ISSUE THREAD

**Issue by baskar-67** [latex3/tagging-project#746]
Dear Sir,
[sample.txt](https://github.com/user-attachments/files/17491461/sample.txt)
Our template stores the abstract content in a box and displays it in \maketitle below the date command. However, when I include the tagpdf package, the abstract moves near the root tag instead of below the date command. I have attached a small sample. Additionally, the tagpdf error shows the following:
! Package tagpdf Error: The number of automatic begin (3) and end (2)
(tagpdf)                text-unit para hooks differ!
For immediate help type H <return>.
 ...                                              
l.47 \end{document}
? 

! Package tagpdf Error: The number of automatic begin (6) and end (5) text
(tagpdf)                para hooks differ!

For immediate help type H <return>.
 ...                                              
                                                  
l.47 \end{document}

Thanks and regards
Baskaran NK

**Comment by baskar-67** [comment]
Dear Madam,
Our template automates table formatting based on its width, allowing us to place it in a single column, double column, rotate it to landscape, use side captions, or create long tables using boxes. In these scenarios, boxes are necessary. However, when we apply tagpdf, the text is directed to the root element. This is just one example, and there are many similar elements. Please provide a solution for applying box content in the same place within tagpdf.
Thanks and regards
Baskaran NK

**Comment by u-fischer** [comment]
I'm closing this question as complete. Please open a new issue with  a complete example for your table question. Moving boxes containing tagging structure is as I wrote non-trivial, there isn't yet a general answer  how to handle them.

**Comment by baskar-67** [comment]
Thank you Madam

**Comment by car222222** [comment]
😀
