### ISSUE TITLE
Tagging heirarchy: <Part> wrapping each <P> within a <Sect>

### ISSUE THREAD

**Issue by John02139** [latex3/tagging-project#776]
In the following example, Acrobat shows that each paragraph in a section is wrapped as a separate part, and that title is wrapped as a paragraph inside a paragraph.   I think  that `<Part>` should not be a child of `<Sect>`, and that `<P>` should not be a child of `<P>`. 

```
\DocumentMetadata 
{
	testphase={phase-III,firstaid,title},
	pdfstandard = ua-2,%a-4f,
	pdfversion  = 2.0,
	lang		= en-US,
	uncompress,
}
\documentclass{article}

\title{Title}
\author{Author}

\begin{document}
\maketitle

\section{A section}

A paragraph.

And more words.

And still more words.

\end{document}  
```
<img width="697" alt="Screenshot 2024-12-30 at 7 42 05 AM" src="https://github.com/user-attachments/assets/5b05ebf4-db47-4cd2-9cc2-290abb832752" />

<img width="395" alt="Screenshot 2024-12-30 at 7 41 39 AM" src="https://github.com/user-attachments/assets/ab80a711-1ba5-4ee7-9b75-6533bb57f580" />

**Comment by u-fischer** [comment]
the actual tags are these

![image](https://github.com/user-attachments/assets/99f635d8-130f-4410-b023-413127e2077a)

so `text-unit -> Title -> text -> content`.  With pdf 2.0 rolemapping applied this give `Part -> Title -> P -> content`  and that is allowed and fine.

What you see in adobe is a sort of "pdf1.7 fallback" as the reader doesn't fully support pdf 2.0 yet. We probably could map `Title` to `Part` or `Div` instead in this case to avoid this problem.

> I think that <Part> should not be a child of <Sect>

Part can be a child of Sect and this setup is by design.

**Comment by John02139** [comment]
Thanks for this clarification.  Glad that the problems are on my end.

I can see where to change tag role mapping in Acrobat - is the necessary set of changes for 2.0 tabulated someplace?  I have some customized codes to check.

Also, could you elaborate on  Sect -> Part -> Paragraph ?   I had expected Sect -> Paragraph (as claimed by some sources online).

**Comment by u-fischer** [comment]
You can get the standards (for free) here https://pdfa.org/sponsored-standards/. The relevant standard for the parent-child rules is ISO TS 32005:2023. (But I think we should change the role of Title here.)

You can find some background about the LaTeX tagging of paragraphs in section 3 of latex-lab-block.pdf.

**Comment by John02139** [comment]
Many thanks. I will look at those sources.

**Comment by car222222** [comment]
@John02139 
But note that the 32005 document is currently being revised, and there will be a few changes to the hierarchy rules.
