### ISSUE TITLE
Compatibility issue with amsthm

### ISSUE THREAD

**Issue by mathmandan** [latex3/tagging-project#83]
```
\DocumentMetadata{testphase=phase-III}

\documentclass{article}

\usepackage{amsthm} % causes error. Compiles fine if either this line, or the first line, or both, is commented out.

\newtheorem{thrm}{Theorem}
 
\begin{document}

Hello.

\begin{thrm}
The limit of a sum is the sum of the limits.
\end{thrm}

\end{document}

```
When trying to compile the above document, I get the following error:

`! Package tagpdf Error: there is no open structure on the stack`

If I comment out either the `\DocumentMetadata{testphase=phase-III}` line, or the `\usepackage{amsthm}` line, or both, then it compiles as expected.

Or if I leave both lines in, but I comment out the `\begin{thrm}` and `\end{thrm}` lines, it will also compile.

I am using TeXworks Version 0.69 (MiKTeX 24.4) in Windows 11 Enterprise. I have used the MiKTeX console to update all packages as of today (June 17, 2024). As of right now if I check for updates in the MiKTeX console, it shows "There are currently no updates available."  I get the same issue using LuaLaTeX, pdfLaTeX, or XeLaTeX.

This issue was posted as [this TeX Stackexchange question](https://tex.stackexchange.com/questions/720793/possible-compatibility-issue-between-tagpdf-and-amsthm).

**Comment by u-fischer** [comment]
A fix has been added in firstaid. So with the next release it will compile and be correctly tagged with

~~~~
\DocumentMetadata{testphase={phase-III,firstaid}}
~~~~

**Comment by mbertucci47** [comment]
I think this can be closed
